language: node_js
node_js:
  - "8"
  - "9"
services:
  - mysql
install:
  - npm install
before_script:
  - npm run to migration:run
  - npm run client:build
script:
  - npm run test
  - npm run server:start
