language: node_js
node_js:
  - "8"
  - "9"
services:
  - mysql
cache: yarn
before_install:
  - mysql -e 'CREATE DATABASE qappa;'
  - mysql -e 'CREATE DATABASE qappa_test;'
install:
  - yarn
before_script:
  - yarn server:lint
  - yarn client:lint
  - yarn to migration:run
  - yarn client:build
script:
  - yarn test
